name: Vitest Report Coverage
on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: 'Install Deps'
        run: npm ci
  
      - name: 'Test'
        run: npm run vitest --coverage.enabled true

      - name: 'Report Coverage'
        if: always() 
        uses: davelosert/vitest-coverage-report-action@v2